[package]
name = "xenon-log-upload"
version = "1.0.0"
authors = ["aspen <aspenuwu@protonmail.com>"]
edition = "2018"

[dependencies]
anyhow = "1.0.38"
reqwest = { version = "0.11.2", default-features = false, features = ["native-tls", "json"] }
serde = "1.0.124"
